services:
  - type: web
    name: Avenue One Agency
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn core.wsgi:application

web: gunicorn core.wsgi:application
